export const PERF_MARKS = {
  contextReceived: "context_received",
  bootstrapPreviewRendered: "bootstrap_preview_rendered",
  mountAppStart: "mount_app_start",
  mountAppEnd: "mount_app_end",
  analysisStart: "analysis_start",
  analysisEnd: "analysis_end",
  writingChunkLoaded: "writing_chunk_loaded",
  writingPreflightStart: "writing_preflight_start",
  writingPreflightEnd: "writing_preflight_end",
  milkdownCreateStart: "milkdown_create_start",
  milkdownParserReady: "milkdown_parser_ready",
  milkdownStateReady: "milkdown_state_ready",
  milkdownViewReady: "milkdown_view_ready",
  milkdownCreateEnd: "milkdown_create_end",
  roundtripProofStart: "roundtrip_proof_start",
  roundtripProofEnd: "roundtrip_proof_end",
  fullProofParseStart: "full_proof_parse_start",
  fullProofParseEnd: "full_proof_parse_end",
  fullProofSerializeStart: "full_proof_serialize_start",
  fullProofSerializeEnd: "full_proof_serialize_end",
  fullProofClassifyStart: "full_proof_classify_start",
  fullProofClassifyEnd: "full_proof_classify_end",
  writingEnableStart: "writing_enable_start",
  writingEnableEnd: "writing_enable_end",
  writingFocusStart: "writing_focus_start",
  writingFocusEnd: "writing_focus_end",
  writingInteractive: "writing_interactive",
  inputStart: "input_start",
  transactionStart: "transaction_start",
  transactionToViewEnd: "transaction_to_view_end",
  transactionToMarkdownEnd: "transaction_to_markdown_end",
  mutationProofStart: "mutation_proof_start",
  mutationProofEnd: "mutation_proof_end",
  canonicalCommitStart: "canonical_commit_start",
  canonicalCommitEnd: "canonical_commit_end",
  projectionSchedule: "projection_schedule",
} as const;

export const PERF_MEASURES = {
  contextToPreview: "context_to_preview_ms",
  contextToApp: "context_to_app_ms",
  contextToWritingInteractive: "context_to_writing_interactive_ms",
  analysis: "analysis_ms",
  writingPreflight: "writing_preflight_ms",
  milkdownCreate: "milkdown_create_ms",
  milkdownSetup: "milkdown_setup_ms",
  milkdownInitialState: "milkdown_initial_state_ms",
  milkdownInitialView: "milkdown_initial_view_ms",
  milkdownTail: "milkdown_tail_ms",
  writingTaskNodeViews: "writing_task_node_views_ms",
  writingFoldingDecorations: "writing_folding_decorations_ms",
  roundtripProof: "roundtrip_proof_ms",
  fullProofParse: "full_proof_parse_ms",
  fullProofSerialize: "full_proof_serialize_ms",
  fullProofClassify: "full_proof_classify_ms",
  proofToEnable: "proof_to_enable_ms",
  writingEnable: "writing_enable_ms",
  writingFocus: "writing_focus_ms",
  mutationProof: "mutation_proof_ms",
  canonicalCommit: "canonical_commit_ms",
  inputToCanonical: "input_to_canonical_ms",
  transactionToView: "transaction_to_view_ms",
  transactionToMarkdown: "transaction_to_markdown_ms",
  transactionToCanonical: "transaction_to_canonical_ms",
  projectionSchedule: "projection_schedule_ms",
} as const;

export type PerfMarkName = typeof PERF_MARKS[keyof typeof PERF_MARKS];
export type PerfMeasureName = typeof PERF_MEASURES[keyof typeof PERF_MEASURES];
